import type { Metadata } from "next";
import { Geist, Geist_Mono, K2D } from "next/font/google";
import  localFont from "next/font/local"
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const IranSansWeb = localFont({
  src : "../assets/fonts/IRANSansWeb.ttf",
  variable : "--font-IranSans"
})
const K2DSans = K2D({
  variable: "--font-K2d",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${K2DSans.variable} ${IranSansWeb.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
